import datetime
from dataclasses import dataclass

@dataclass
class Root:
    PersonId: int
    PersonNumber: str
    CorrespondenceLanguage: CorrespondenceLanguage
    BloodType: BloodType
    DateOfBirth: DateOfBirth
    DateOfDeath: DateOfDeath
    CountryOfBirth: CountryOfBirth
    RegionOfBirth: RegionOfBirth
    TownOfBirth: TownOfBirth
    ApplicantNumber: ApplicantNumber
    CreatedBy: str
    CreationDate: str
    LastUpdatedBy: str
    LastUpdateDate: str
    workRelationships: workRelationships

@dataclass
class workRelationships:
    items: list[itemsItem]

@dataclass
class itemsItem:
    PeriodOfServiceId: int
    LegislationCode: str
    LegalEntityId: int
    LegalEmployerName: LegalEmployerName
    WorkerType: str
    PrimaryFlag: bool
    StartDate: str
    LegalEmployerSeniorityDate: LegalEmployerSeniorityDate
    EnterpriseSeniorityDate: EnterpriseSeniorityDate
    OnMilitaryServiceFlag: bool
    WorkerNumber: WorkerNumber
    ReadyToConvertFlag: ReadyToConvertFlag
    TerminationDate: TerminationDate
    NotificationDate: NotificationDate
    LastWorkingDate: LastWorkingDate
    RevokeUserAccess: RevokeUserAccess
    RecommendedForRehire: str
    RecommendationReason: RecommendationReason
    RecommendationAuthorizedByPersonId: RecommendationAuthorizedByPersonId
    CreatedBy: str
    CreationDate: str
    LastUpdatedBy: str
    LastUpdateDate: str
    assignments: assignments

@dataclass
class assignments:
    items: list[itemsItem1]

@dataclass
class itemsItem1:
    AssignmentId: int
    AssignmentNumber: str
    AssignmentName: str
    ActionCode: str
    ReasonCode: ReasonCode
    EffectiveStartDate: str
    EffectiveEndDate: str
    EffectiveSequence: int
    EffectiveLatestChange: str
    BusinessUnitId: int
    BusinessUnitName: str
    AssignmentType: str
    AssignmentStatusTypeId: int
    AssignmentStatusTypeCode: str
    AssignmentStatusType: str
    SystemPersonType: str
    UserPersonTypeId: int
    UserPersonType: str
    ProposedUserPersonTypeId: ProposedUserPersonTypeId
    ProposedUserPersonType: ProposedUserPersonType
    ProjectedStartDate: ProjectedStartDate
    ProjectedEndDate: ProjectedEndDate
    PrimaryFlag: bool
    PrimaryAssignmentFlag: bool
    PositionId: PositionId
    PositionCode: PositionCode
    SynchronizeFromPositionFlag: bool
    JobId: JobId
    JobCode: JobCode
    GradeId: GradeId
    GradeCode: GradeCode
    GradeLadderId: GradeLadderId
    GradeLadderName: GradeLadderName
    GradeStepEligibilityFlag: bool
    GradeCeilingStepId: GradeCeilingStepId
    GradeCeilingStep: GradeCeilingStep
    DepartmentId: DepartmentId
    DepartmentName: DepartmentName
    ReportingEstablishmentId: ReportingEstablishmentId
    ReportingEstablishmentName: ReportingEstablishmentName
    LocationId: LocationId
    LocationCode: LocationCode
    WorkAtHomeFlag: bool
    AssignmentCategory: AssignmentCategory
    WorkerCategory: WorkerCategory
    PermanentTemporary: PermanentTemporary
    FullPartTime: FullPartTime
    ManagerFlag: bool
    HourlySalariedCode: HourlySalariedCode
    NormalHours: NormalHours
    Frequency: Frequency
    StartTime: StartTime
    EndTime: EndTime
    SeniorityBasis: str
    ProbationPeriod: ProbationPeriod
    ProbationPeriodUnit: ProbationPeriodUnit
    ProbationEndDate: ProbationEndDate
    NoticePeriod: NoticePeriod
    NoticePeriodUOM: NoticePeriodUOM
    WorkTaxAddressId: WorkTaxAddressId
    ExpenseCheckSendToAddress: ExpenseCheckSendToAddress
    RetirementAge: RetirementAge
    RetirementDate: RetirementDate
    LabourUnionMemberFlag: LabourUnionMemberFlag
    UnionId: UnionId
    UnionName: UnionName
    BargainingUnitCode: BargainingUnitCode
    CollectiveAgreementId: CollectiveAgreementId
    CollectiveAgreementName: CollectiveAgreementName
    InternalBuilding: InternalBuilding
    InternalFloor: InternalFloor
    InternalOfficeNumber: InternalOfficeNumber
    InternalMailstop: InternalMailstop
    DefaultExpenseAccount: DefaultExpenseAccount
    PeopleGroup: PeopleGroup
    CreatedBy: str
    CreationDate: str
    LastUpdatedBy: str
    LastUpdateDate: str
