import org.joda.time.DateTime

case class Root(
    AddressId: Int,
    EffectiveStartDate: String,
    EffectiveEndDate: String,
    AddressLine1: String,
    AddressLine2: AddressLine2,
    AddressLine3: AddressLine3,
    AddressLine4: AddressLine4,
    TownOrCity: String,
    Region1: Region1,
    Region2: Region2,
    Region3: Region3,
    Country: String,
    PostalCode: PostalCode,
    LongPostalCode: LongPostalCode,
    AddlAddressAttribute1: AddlAddressAttribute1,
    AddlAddressAttribute2: AddlAddressAttribute2,
    AddlAddressAttribute3: AddlAddressAttribute3,
    AddlAddressAttribute4: AddlAddressAttribute4,
    AddlAddressAttribute5: AddlAddressAttribute5,
    CreatedBy: String,
    CreationDate: String,
    LastUpdatedBy: String,
    LastUpdateDate: String,
    PersonAddrUsageId: Int,
    AddressType: String,
    PrimaryFlag: Boolean
)
